### ISSUE TITLE
Suggestions & Stuff (Not Issue)

### ISSUE THREAD

**Issue by chicken-nugget1104** [SaiyanGonzalez01/Minecraft-Old-School-ReDefault#13]
i guess we just
suggest concepts here
and then try to add them if we can???
idk

**Comment by SaiyanGonzalez01** [comment]
oh I got a good suggestion! How about we fix the importing worlds bug?

**Comment by chicken-nugget1104** [comment]
> oh I got a good suggestion! How about we fix the importing worlds bug?

ok
oh i also have one!!!
lets make the done button in the profile thing not work until you have a username
oh also lets try and add a button so you can go back to that-
but you can also change your username in the multiplayer thing so maybe we remove that? idk

**Comment by SaiyanGonzalez01** [comment]
> but you can also change your username in the multiplayer thing so maybe we remove that? idk

Lets keep that, because what if you have an alt and want to fast change the user so you can join the server quickly in your alt

**Comment by chicken-nugget1104** [comment]
> > but you can also change your username in the multiplayer thing so maybe we remove that? idk
> 
> Lets keep that, because what if you have an alt and want to fast change the user so you can join the server quickly in your alt

oh true ok yeah

idea: can i become collaborator
making PR's is tiring

**Comment by SaiyanGonzalez01** [comment]
Sure, I was gonna ask you actually lol

**Comment by SaiyanGonzalez01** [comment]
i'll send the invite

**Comment by chicken-nugget1104** [comment]
> i'll send the invite

epicness do you have discord
if so my discord is filledpaintbucket

**Comment by SaiyanGonzalez01** [comment]
my discord was deleted because my phone got wiped and I forgot to save the passwords and stuff :(

**Comment by SaiyanGonzalez01** [comment]
but I do have revlot

**Comment by chicken-nugget1104** [comment]
> but I do have revlot

revolt?
dont got that
but i can make an account on there

**Comment by SaiyanGonzalez01** [comment]
its like discord with nitro stuff already unlocked for you and you can change stuff with css and more

**Comment by chicken-nugget1104** [comment]
> its like discord with nitro stuff already unlocked for you and you can change stuff with css and more

ok cool im on it
filledpaintbucket is the username

**Comment by SaiyanGonzalez01** [comment]
nice, but I need the little numbers that come with your user so I can add you, so its like 'user#0118' as an example

**Comment by chicken-nugget1104** [comment]
> nice, but I need the little numbers that come with your user so I can add you, so its like 'user#0118' as an example

ah ok
7215

**Comment by SaiyanGonzalez01** [comment]
so "filledpaintbucket#7215"?

**Comment by chicken-nugget1104** [comment]
> so "filledpaintbucket#7215"?

yep

**Comment by SaiyanGonzalez01** [comment]
quick question, why did you start pull requesting on my project? what was about it that made you want to contribute to it? I still see my project as a little hobby that really no-one knows about, so why did you want to help?

**Comment by chicken-nugget1104** [comment]
> quick question, why did you start pull requesting on my project? what was about it that made you want to contribute to it? I still see my project as a little hobby that really no-one knows about, so why did you want to help?

because
i thought it was neat

**Comment by SaiyanGonzalez01** [comment]
🥲 dam, oh and I sent friend request

**Comment by SaiyanGonzalez01** [comment]
well guess I should close this
