### ISSUE TITLE
2 devs fix a bug that they both don't know how it even started

### ISSUE THREAD

**Issue by chicken-nugget1104** [SaiyanGonzalez01/Minecraft-Old-School-ReDefault#9]
why do you keep undoing the minecraft changes if it compiles????
i dont get it

**Comment by chicken-nugget1104** [comment]
also you broke truncating the message
i have a fix ready

**Comment by SaiyanGonzalez01** [comment]
Dude idk why it breaks, it just does, I try to fix it and it makes more problems so I have to revert stuff again and again, I don't want to revert stuff, but I have to do it for it to work. Its literally like a landmine, one error sets a change reaction, so I just have to revert it to fix. It compiles but then it crashes, so I'm trying not to make it do that yet it does.

**Comment by chicken-nugget1104** [comment]
> Dude idk why it breaks, it just does, I try to fix it and it makes more problems so I have to revert stuff again and again, I don't want to revert stuff, but I have to do it for it to work. Its literally like a landmine, one error sets a change reaction, so I just have to revert it to fix. It compiles but then it crashes, so I'm trying not to make it do that yet it does.

doesnt happen to me???
like i dont know how to reproduce this
what does the crash say?

**Comment by SaiyanGonzalez01** [comment]
Its more of a freeze than a crash, it just stays stuck on the Mojang logo and never leaves it, so either its taking a really long time to load, (I waited 1 hour last time, and didn't load to the skin select) or its the code that broke it.

**Comment by SaiyanGonzalez01** [comment]
And again it gave me another error in the terminal

![Screenshot 2024-12-06 8 37 52 PM](https://github.com/user-attachments/assets/a39d8bbc-509e-4402-a729-3c03a777c908)

**Comment by chicken-nugget1104** [comment]
> Its more of a freeze than a crash, it just stays stuck on the Mojang logo and never leaves it, so either its taking a really long time to load, (I waited 1 hour last time, and didn't load to the skin select) or its the code that broke it.

hmmm
doesnt occur for me
can you re-upload the un-working mc.java so i can test it thru the github.io?

**Comment by chicken-nugget1104** [comment]
because it WANTS doPrints
it may be setting doPrints as the error but idk

> And again it gave me another error in the terminal

**Comment by chicken-nugget1104** [comment]
> > Its more of a freeze than a crash, it just stays stuck on the Mojang logo and never leaves it, so either its taking a really long time to load, (I waited 1 hour last time, and didn't load to the skin select) or its the code that broke it.
> 
> hmmm doesnt occur for me can you re-upload the un-working mc.java so i can test it thru the github.io?

@SaiyanGonzalez01

**Comment by SaiyanGonzalez01** [comment]
> hmmm
> doesnt occur for me
> can you re-upload the un-working mc.java so i can test it thru the github.io?

I don't think I have it, I reverted it remember? Maybe in the files history

**Comment by chicken-nugget1104** [comment]
> > hmmm
> > doesnt occur for me
> > can you re-upload the un-working mc.java so i can test it thru the github.io?
> 
> I don't think I have it, I reverted it remember? Maybe in the files history

yeah just go thru the commit history
on github to find it

**Comment by SaiyanGonzalez01** [comment]
Other than that I remember that many errors for other files that had to do with the printing thing you added

**Comment by chicken-nugget1104** [comment]
> Other than that I remember that many errors for other files that had to do with the printing thing you added

was it because you deleted doPrints
deleting something other files use is obviously gonna cause an error

**Comment by SaiyanGonzalez01** [comment]
maybe, what files did you edit that added the prints so I can add it back, oh and commit 486e2c9 is with the Minecraft.java change

**Comment by chicken-nugget1104** [comment]
> maybe, what files did you edit that added the prints so I can add it back, oh and commit [486e2c9](https://github.com/SaiyanGonzalez01/Minecraft-Old-School-ReDefault/commit/486e2c9e1802af3eaff10728cca8fc55c1fb59b0) is with the Minecraft.java change

uh i know i did minecraft.java
ingamemenu.java
i think maybe the title screen
the gamesettings.java
uh i forgo

i have a bat file to search for things in the code tho
so hold on lemme run it

**Comment by SaiyanGonzalez01** [comment]
oh, well my project might be cooked 💀

**Comment by chicken-nugget1104** [comment]
> oh, well my project might be cooked 💀

nah bro
hold on ill tell ya

**Comment by chicken-nugget1104** [comment]
Minecraft.java
GuiIngame.java
GameSettings.java
@SaiyanGonzalez01

**Comment by SaiyanGonzalez01** [comment]
Well I do have the download of the whole project in the zip before the errors, so I could just upload the files from that if this is just cooked

**Comment by SaiyanGonzalez01** [comment]
> Minecraft.java
> GuiIngame.java
> GameSettings.java
> @SaiyanGonzalez01
 
Alright so I just download and upload correct?

**Comment by chicken-nugget1104** [comment]
> Well I do have the download of the whole project in the zip before the errors, so I could just upload the files from that if this is just cooked

it really isnt cooked
i hope.
uh
i think i can fix it?
re-upload the mc from this commit please (so i can see this for myself)

[ea515d1](https://github.com/SaiyanGonzalez01/Minecraft-Old-School-ReDefault/commit/ea515d163e66dc65b14eca609f2f05a4d293ec02)

**Comment by chicken-nugget1104** [comment]
> > Well I do have the download of the whole project in the zip before the errors, so I could just upload the files from that if this is just cooked
> 
> it really isnt cooked i hope. uh i think i can fix it? re-upload the mc from this commit please (so i can see this for myself)
> 
> [ea515d1](https://github.com/SaiyanGonzalez01/Minecraft-Old-School-ReDefault/commit/ea515d163e66dc65b14eca609f2f05a4d293ec02)

you can revert after i test

**Comment by SaiyanGonzalez01** [comment]
I pray to the git gods it isn't fried 🙏

**Comment by SaiyanGonzalez01** [comment]
> Well I do have the download of the whole project in the zip before the errors, so I could just upload the files from that if this is just cooked
> 
> it really isnt cooked i hope. uh i think i can fix it? re-upload the mc from this commit please (so i can see this for myself)
> 
> [ea515d1](https://github.com/SaiyanGonzalez01/Minecraft-Old-School-ReDefault/commit/ea515d163e66dc65b14eca609f2f05a4d293ec02)
> 
> you can revert after i test

So I just try to compile right?

**Comment by chicken-nugget1104** [comment]
> > Well I do have the download of the whole project in the zip before the errors, so I could just upload the files from that if this is just cooked
> > it really isnt cooked i hope. uh i think i can fix it? re-upload the mc from this commit please (so i can see this for myself)
> > [ea515d1](https://github.com/SaiyanGonzalez01/Minecraft-Old-School-ReDefault/commit/ea515d163e66dc65b14eca609f2f05a4d293ec02)
> > you can revert after i test
> 
> So I just try to compile right?

yeh

**Comment by SaiyanGonzalez01** [comment]
Alright

**Comment by SaiyanGonzalez01** [comment]
Hold on you said re-upload the mc.java before I compile?

**Comment by chicken-nugget1104** [comment]
> Hold on you said re-upload the mc.java before I compile?

yeah from the commit i sent

**Comment by SaiyanGonzalez01** [comment]
alright done with the re-upload (just copied and pasted it)

**Comment by chicken-nugget1104** [comment]
> alright done with the re-upload (just copied and pasted it)

k tell me when you compile so i can test

**Comment by SaiyanGonzalez01** [comment]
It compiled! I'll add the app.js and app.js.map, then test the link on the readme.md when the thing fully updates

**Comment by chicken-nugget1104** [comment]
> It compiled! I'll add the app.js and app.js.map, then test the link on the readme.md when the thing fully updates

so far so good

**Comment by SaiyanGonzalez01** [comment]
lets not jinx it

**Comment by SaiyanGonzalez01** [comment]
ok the little icon for the update is still orange

**Comment by chicken-nugget1104** [comment]
> ok the little icon for the update is still orange

hm k

**Comment by SaiyanGonzalez01** [comment]
alright its fully updated you can test now

**Comment by SaiyanGonzalez01** [comment]
shoot on my end its still frozen

**Comment by chicken-nugget1104** [comment]
> alright its fully updated you can test now

for me it goes to a completely black screen
hold on i cant open inspect element
lemme try my main coding PC

**Comment by chicken-nugget1104** [comment]
> > alright its fully updated you can test now
> 
> for me it goes to a completely black screen hold on i cant open inspect element lemme try my main coding PC

yeah its just going to a black screen
even on my main coding PC
im not seeing any errors in the log

**Comment by chicken-nugget1104** [comment]
i have an idea but you may not like it

**Comment by SaiyanGonzalez01** [comment]
oh no

**Comment by chicken-nugget1104** [comment]
> oh no

im uploading the minecraft.java i have been using on my netlify app
(minecrafty.netlify.app)

this is my only solution as it works for me

**Comment by SaiyanGonzalez01** [comment]
uh what's wrong with that?

**Comment by SaiyanGonzalez01** [comment]
I could do that probably

**Comment by chicken-nugget1104** [comment]
> uh what's wrong with that?

i have fog code (aka a keybind)
random stuff
unrelated stuff

**Comment by chicken-nugget1104** [comment]
#12

**Comment by chicken-nugget1104** [comment]
woops forgot to remove a ref

**Comment by SaiyanGonzalez01** [comment]
Jesus we are 40+ comments in and we are probably making more problems then solutions, but hopefully the pull request fixes it

**Comment by chicken-nugget1104** [comment]
> Jesus we are 40+ comments in and we are probably making more problems then solutions, but hopefully the pull request fixes it

i hope
as it works for me
always has
i dont know what is happening anyway

**Comment by chicken-nugget1104** [comment]
so are you compiling or

**Comment by SaiyanGonzalez01** [comment]
yea I'm compiling

**Comment by SaiyanGonzalez01** [comment]
it says its successful

**Comment by chicken-nugget1104** [comment]
> yea I'm compiling

k
im optimizing my core.glsl rn by making it do... less?
idk
more math = bad apparently
even tho it clearly did less lag

**Comment by chicken-nugget1104** [comment]
ok question @SaiyanGonzalez01 when did the issue start

**Comment by SaiyanGonzalez01** [comment]
I've been trying to fix it for a while so I forgot

**Comment by chicken-nugget1104** [comment]
> I've been trying to fix it for a while so I forgot

breh
that would be rlly helpful to know

**Comment by SaiyanGonzalez01** [comment]
but finally... inner-peace

![Screenshot 2024-12-06 9 22 54 PM](https://github.com/user-attachments/assets/243ae323-3978-4e44-ba4e-f00b8d47595b)

You did it! Thank you so much actually I was about to lose my mind over this

**Comment by chicken-nugget1104** [comment]
> but finally... inner-peace
> 
> ![Screenshot 2024-12-06 9 22 54 PM](https://private-user-images.githubusercontent.com/153963453/393464301-243ae323-3978-4e44-ba4e-f00b8d47595b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Mzg1NjgsIm5iZiI6MTczMzUzODI2OCwicGF0aCI6Ii8xNTM5NjM0NTMvMzkzNDY0MzAxLTI0M2FlMzIzLTM5NzgtNGU0NC1iYTRlLWYwMGI4ZDQ3NTk1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwMjI0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2EyNThhY2QwZWRlYzc1YjI1ZDFmZWU0YjI2YTJjYTY2M2NiMTFmNWQ4NjZhYWJjZGI5YzU3MWU0MWEyNDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tO4wwnGO6AFFc3xIkE7kaobnvlNfh27aJuMqIBsobSE)
> 
> You did it! Thank you so much actually I was about to lose my mind over this

dang i did it
i dont even know how i did it

**Comment by SaiyanGonzalez01** [comment]
lmao

**Comment by chicken-nugget1104** [comment]
welp
guess i can close this
will re-open if i got any "questions"
or if we have problems again
